datasource:
  batch:
      initialize: true
      driver-class-name: "org.h2.Driver"
      url: "jdbc:h2:mem:batch;MVCC=true;DB_CLOSE_DELAY=-1;MODE=MySQL"
      user-name: "sa"
      password: ""
      initial-size: 10
      max-active: 10
      max-idle: 10
      min-idle: 10
      max-wait: 3000
  mysql:
      initialize: true
      driver-class-name: "org.h2.Driver"
      url: "jdbc:h2:mem:test2;MVCC=true;DB_CLOSE_DELAY=-1;MODE=MySQL"
      user-name: "sa"
      password: ""
      initial-size: 10
      max-active: 10
      max-idle: 10
      min-idle: 10
      max-wait: 3000
      
spring:
  batch:
    job:
      enabled: false